### ISSUE TITLE
Error running add nsw/topographic v2.0.0

### ISSUE THREAD

**Issue by clint-lawrence** [mholling/nswtopo#39]
I'm getting the following error trying to create a add topographic layer to a map
/users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/geometry/vector.rb:69:in `perp': undefined method `-@' for [2650.0, -3737.5]:Array (NoMethodError)

Steps to reproduce:
```
nswtopo init --dimensions 210,297 --coords 151.540,-32.842 map.tgz
nswtopo add map.tgz nsw/vegetation-spot5
nswtopo add map.tgz nsw/topographic
```
nswtopo 2.0.0
ruby 2.6.2p47

**Comment by clint-lawrence** [comment]
Full traceback from that last command is
```
clintlawrence:~/dev/nswtopo/notarace$nswtopo add map.tgz nsw/topographic
nswtopo: empty layer: nsw.topographic.plantation-horticulture
nswtopo: empty layer: nsw.topographic.urban-areas
nsw.topographic.contours: retrieved 0 of 177 featuresTraceback (most recent call last):
	23: from /Users/clintlawrence/bin/nswtopo:409:in `<main>'
	22: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/archive.rb:58:in `open'
	21: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/archive.rb:58:in `open'
	20: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/archive.rb:65:in `block in open'
	19: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:29:in `new'
	18: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/archive.rb:66:in `block (2 levels) in open'
	17: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/archive.rb:66:in `tap'
	16: from /Users/clintlawrence/bin/nswtopo:418:in `block in <main>'
	15: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo.rb:123:in `add'
	14: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo.rb:123:in `tap'
	13: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo.rb:129:in `block in add'
	12: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/map.rb:185:in `add'
	11: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/map.rb:185:in `inject'
	10: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/map.rb:185:in `each'
	 9: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/map.rb:188:in `block in add'
	 8: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/layer/vector.rb:10:in `create'
	 7: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/gis/geojson/collection.rb:82:in `clip!'
	 6: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/gis/geojson/collection.rb:82:in `map!'
	 5: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/gis/geojson/collection.rb:83:in `block in clip!'
	 4: from /usr/local/Cellar/ruby/2.6.2/lib/ruby/2.6.0/forwardable.rb:230:in `clip'
	 3: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/gis/geojson/multi_line_string.rb:7:in `clip'
	 2: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/geometry/vector_sequence.rb:3:in `perps'
	 1: from /users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/geometry/vector_sequence.rb:3:in `map'
/users/clintlawrence/dev/nswtopo/nswtopo/lib/nswtopo/geometry/vector.rb:69:in `perp': undefined method `-@' for [2650.0, -3737.5]:Array (NoMethodError)
```

**Comment by ZeevG** [comment]
Interesting, I am also getting a similar error.

```
➜  nsw-topo nswtopo add map.tgz nsw/topographic         
nsw.topographic.plantation-horticulture: retrieved 0 of 69 featuresTraceback (most recent call last):
	30: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	29: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	28: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/bin/nswtopo:23:in `<main>'
	27: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/bin/nswtopo:23:in `load'
	26: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/bin/nswtopo:409:in `<top (required)>'
	25: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/archive.rb:58:in `open'
	24: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/archive.rb:58:in `open'
	23: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/archive.rb:65:in `block in open'
	22: from /Users/zgilovitz/.rvm/rubies/ruby-2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/package/tar_reader.rb:29:in `new'
	21: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/archive.rb:66:in `block (2 levels) in open'
	20: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/archive.rb:66:in `tap'
	19: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/bin/nswtopo:418:in `block in <top (required)>'
	18: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo.rb:123:in `add'
	17: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo.rb:123:in `tap'
	16: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo.rb:129:in `block in add'
	15: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/map.rb:185:in `add'
	14: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/map.rb:185:in `inject'
	13: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/map.rb:185:in `each'
	12: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/map.rb:188:in `block in add'
	11: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/layer/vector.rb:10:in `create'
	10: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/gis/geojson/collection.rb:82:in `clip!'
	 9: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/gis/geojson/collection.rb:82:in `map!'
	 8: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/gis/geojson/collection.rb:83:in `block in clip!'
	 7: from /Users/zgilovitz/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/forwardable.rb:230:in `clip'
	 6: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/gis/geojson/multi_polygon.rb:7:in `clip'
	 5: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/gis/geojson/multi_polygon.rb:7:in `inject'
	 4: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/gis/geojson/multi_polygon.rb:7:in `each'
	 3: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/gis/geojson/multi_polygon.rb:9:in `block in clip'
	 2: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/geometry/vector_sequence.rb:3:in `perps'
	 1: from /Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/geometry/vector_sequence.rb:3:in `map'
/Users/zgilovitz/.rvm/gems/ruby-2.6.0/gems/nswtopo-2.0.0/lib/nswtopo/geometry/vector.rb:69:in `perp': undefined method `-@' for [85862.40910849116, -8893.249861466356]:Array (NoMethodError)
```

I tried adding a specific layer within `nsw/topographic` and had the same problem. `map.tgz` 
attached. [map.tgz.zip](https://github.com/mholling/nswtopo/files/3063545/map.tgz.zip)
My Ruby isn't that great, but I'll have a dig through the stack trace later.

**Comment by ZeevG** [comment]
Quite a hack but I solved this by renaming the Segment.difference method. There must be something overriding that method name.

**Comment by clint-lawrence** [comment]
@ZeevG can you be more specific? Or push the change you made on a fork perhaps?

**Comment by ZeevG** [comment]
The specific change I made was to rename the `difference` method to `difference_seg` https://github.com/mholling/nswtopo/blob/master/lib/nswtopo/geometry/segment.rb#L10 I then updated all references which seemed to operate on an array to also use `difference_seg`

I'm still not sure why this worked. When I was debugging it, the difference method within segment wasn't being executed - something else was. I tried renaming it, and it started getting executed. 🤷‍♂️ This is all a bit too Ruby specific for me.

Let me know how you go.

**Comment by clint-lawrence** [comment]
Same worked for me... very strange

**Comment by ondrejivanic** [comment]
I've run into the same issue with

```
(topo_maps) ondrej@server:~/Projects/nswtopo$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

(topo_maps) ondrej@server:~/Projects/nswtopo$ gdalinfo --version
GDAL 3.0.2, released 2019/10/28
```

When I run this in Ubuntu 19.04 with ruby 2.5 everything is fine.

```
docker run -it ubuntu:19.04 /usr/bin/bash

root@ae5d88856bd2:/# ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

root@ae5d88856bd2:/# gdalinfo gdalinfo --version
GDAL 2.4.0, released 2018/12/14
```

**Comment by ondrejivanic** [comment]
Downgrading `ruby` to `2.5.1` solved this for me:

```
conda install -c conda-forge gdal=2.3 imagemagick 'ruby<2.6'
```
