### ISSUE TITLE
undefined method "deep_merge"

### ISSUE THREAD

**Issue by cnschulz** [mholling/nswtopo#9]
Gday, 

Ive just installed all the prerequisites and given your script a first run. Ive encountered this error and would love some help in getting it working.

Cheers

c.

nswtopo.rb:46:in `deep_merge': undefined method `inject' for false:FalseClass (NoMethodError)                                                                           from nswtopo.rb:2800:in `each'                                                  from nswtopo.rb:2800:in `inject'                                                from nswtopo.rb:2800:in `run'                                                   from nswtopo.rb:3145:in `<main>'

**Comment by cnschulz** [comment]
FIXED: OSGeo4W did not install correctly. Reinstall resolved issue.
